# Generated by Django 5.0.4 on 2024-05-06 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 14, 46, 30, 478472)),
        ),
    ]
