# Generated by Django 5.0.4 on 2024-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0002_alter_movieorder_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
